# 💎⚡ HYPERFOCUS DEV COMMUNITY FUNDING ⚡💎
# Support the neurodivergent-friendly development revolution!

github: welshDog
patreon: hyperfocuszone
ko_fi: hyperfocuszone
custom: 
  - "https://hyperfocuszone.com/support"
  - "https://discord.gg/2fpxEsUyfa"
  - "mailto:business@hyperfocuszone.com"
